const arr = [
    "INR",
    "AFN",
    "DZD",
    "ARS",
    "AMD",
    "AWG",
    "AUD",
    "AZN",
    "BSD",
    "BHD",
    "THB",
    "PAB",
    "BBD",
    "BYN",
    "BZD",
    "BMD",
    "VEF",
    "VED",
    "BOB",
    "BRL",
    "BND",
    "BGN",
    "BIF",
    "CVE",
    "CAD",
    "KYD",
    "XOF",
    "XAF",
    "XPF",
    "CLP",
    "COP",
    "KMF",
    "CDF",
    "BAM",
    "NIO",
    "CRC",
    "CUP",
    "CZK",
    "GMD",
    "DKK",
    "MKD",
    "DJF",
    "STN",
    "DOP",
    "VND",
    "XCD",
    "EGP",
    "SVC",
    "ETB",
    "EUR",
    "FKP",
    "FJD",
    "HUF",
    "GHS",
    "GIP",
    "HTG",
    "PYG",
    "GNF",
    "GYD",
    "HKD",
    "UAH",
    "ISK",
    "IRR",
    "IQD",
    "JMD",
    "JOD",
    "KES",
    "PGK",
    "LAK",
    "HRK",
    "KWD",
    "MWK",
    "AOA",
    "MMK",
    "GEL",
    "LBP",
    "ALL",
    "HNL",
    "SLE",
    "LRD",
    "LYD",
    "SZL",
    "LSL",
    "MGA",
    "MYR",
    "MUR",
    "MXN",
    "MXV",
    "MDL",
    "MAD",
    "MZN",
    "BOV",
    "NGN",
    "ERN",
    "NAD",
    "NPR",
    "ANG",
    "ILS",
    "TWD",
    "NZD",
    "BTN",
    "KPW",
    "NOK",
    "PEN",
    "MRU",
    "PKR",
    "MOP",
    "TOP",
    "CUC",
    "UYU",
    "PHP",
    "GBP",
    "BWP",
    "QAR",
    "GTQ",
    "ZAR",
    "OMR",
    "KHR",
    "RON",
    "MVR",
    "IDR",
    "RUB",
    "RWF",
    "SHP",
    "SAR",
    "XDR",
    "RSD",
    "SCR",
    "SGD",
    "SBD",
    "KGS",
    "SOS",
    "TJS",
    "SSP",
    "LKR",
    "XSU",
    "SDG",
    "SRD",
    "SEK",
    "CHF",
    "SYP",
    "BDT",
    "WST",
    "TZS",
    "KZT",
    "TTD",
    "MNT",
    "TND",
    "TRY",
    "TMT",
    "AED",
    "UGX",
    "CLF",
    "COU",
    "UYI",
    "USD",
    "USN",
    "UZS",
    "VUV",
    "CHE",
    "CHW",
    "KRW",
    "YER",
    "JPY",
    "CNY",
    "ZMW",
    "ZWL",
    "PLN",
];

export default arr;

// setSortedDataArray(sortedData)
//         let minmaxIdx = MaxMin(sortedData, currency)
//         setminMax(minmaxIdx)
//         if(isCurrencyExist(sortedData, currency)){
//             Object.entries(sortedData).forEach(function([k,v]){
//                 if(v[1][currency] === undefined){
//                     arr[v[0]] = undefined;
//                     null_index.push(v[0])
//                 }
//                 else arr[v[0]] = v[1][currency]
//             })
            
//             setdArr(arr)
//         } else {
//             setdArr({});
//         }

// export const isCurrencyExist = (data, currency) => {
//     Object.entries(data).forEach(function([k,v]){  // daywise
//         if(v[1][currency] !== undefined) return true;
//     })
//     return false;
// }
// export const daily = (data, currency) => {
//     const arr = {};
//     Object.entries(data).forEach(function([k,v]){  // daywise
//         if(v[1][currency] === undefined) arr[v[0]] = undefined;
//         else arr[v[0]] = v[1][currency]
//     })
//     return arr;
// };